#!/usr/bin/env bash
# to move window either in floating or tiling mode

_curr_win_floating=$(hyprctl activewindow -j | jq -r '.floating')
val=${HYPR_MOVE_VAL:-50}

getVal() {
  case "$1" in
  "r")
    echo "$val 0"
    ;;
  "d")
    echo "0 $val"
    ;;
  "l")
    echo "-$val 0"
    ;;
  "u")
    echo "0 -$val"
    ;;
  esac
}

if [ $# -eq 0 ]; then
  echo "No arguments provided"
  exit 1
fi

if [[ $_curr_win_floating == "true" ]]; then
  # shellcheck disable=SC2046
  hyprctl dispatch moveactive $(getVal "$1")
else
  hyprctl dispatch movewindow "$1"
fi
