#!/usr/bin/env bash
# shellcheck disable=SC2009
_pid="$(hyprctl clients -j | jq -r '.[] | select(.class == "foot-quick") | .pid')"

if [ "$_pid" != "" ]; then
  curr_focused="$(hyprctl activewindow -j | jq -r '.class')"
  if [ "$curr_focused" = "foot-quick" ]; then
    kill -9 "$_pid"
  else
    hyprctl dispatch focuswindow pid:"$_pid"
  fi
else
  foot -a "foot-quick" sh -c "tmux new-session -A -s 'quick-term'" >/dev/null 2>&1 &
  exit 0
fi
